In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("movies.csv")

In [3]:
movies

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

## About this file

The data is succesfully scrapped from imdb about netflix movies and tvshows.This dataset need clever programming knowledge for feature extraction also you can build a RECOMMENDATION system either GENRE prediction model
ABOUT DATA

1. **MOVIES**
         The movie names are given under the column
2. **YEAR**
        The year of movie or tv shows telecast for audience
3. **GENRE**
        The dataset contain many genres most valuable for recommendation system
4. **RATING**
          The audience thought about movie or tv show given
5. **ONE-LINE**
           The short description about movie or tv show for audiences first impression
6. **STARS**
            The casting of art is define under this columns which makes talk between audience 
7. **VOTES**
            The audience express their view under the columns its useful to identify impact make by art 
8. **RUNTIME**
            The duration for runing time of art
9. **GROSS**
            It gives the total amount earned in worldwide

In [4]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    9999 non-null   object
 1   YEAR      9355 non-null   object
 2   GENRE     9919 non-null   object
 3   RATING    8179 non-null   float64
 4   ONE-LINE  9999 non-null   object
 5   STARS     9999 non-null   object
 6   VOTES     8179 non-null   object
 7   RunTime   7041 non-null   float64
 8   Gross     460 non-null    object
dtypes: float64(2), object(7)
memory usage: 703.2+ KB

***Exporting the file into an excel file for manual assessment.***

In [5]:
movies.to_excel("movies.xlsx")

In [6]:
movies.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
4278,Tudo Bem No Natal Que Vem,(2020),"\nComedy, Drama",6.7,\nStuck in a time loop where it's forever Chri...,\n Director:\nRoberto Santucci\n| \n Sta...,"3,672",100.0,NaN
3562,Pete Davidson: Alive from New York,(2020 TV Special),\nComedy,6.1,\nComedian Pete Davidson's intimate and candid...,\n Director:\nJason Orley\n| \n Stars:\n...,"3,278",49.0,NaN
3068,Ahiru no Sora,(2019– ),"\nAnimation, Sport",7.5,"\nHe's short, weak, and has just transferred t...","\n \n Stars:\nCameron Bautsch, \...",451,NaN,NaN
3295,Sarah & Duck,(2013– ),"\nAnimation, Family",8.4,\nSarah is a young British girl whose best fri...,"\n \n Stars:\nTasha Lawrence, \n...",630,7.0,NaN
4648,Dayveon,(2017),\nDrama,6.3,"\nIn the wake of his older brother's death, 13...",\n Director:\nAmman Abbasi\n| \n Stars:\...,501,75.0,$0.00M
9277,Stay Close,NaN,"\nCrime, Drama, Mystery",NaN,\nAdd a Plot\n,"\n \n Stars:\nBethany Antonia, \...",NaN,NaN,NaN
2962,Hayop Ka!,(2020),"\nAnimation, Comedy, Romance",7.1,"\nIn this adult animation, perfume sales cat N...",\n Director:\nAvid Liongoren\n| \n Stars...,181,73.0,NaN
9971,Sonic Prime,(2022– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
7730,La casa de las flores,(2018–2020),"\nComedy, Drama",6.8,\nElena wants to keep her new job a secret. Pa...,"\n Directors:\nAlberto Belli, \nManolo Caro...",143,NaN,NaN
5487,The Unsound,NaN,\nHorror,NaN,\nA psychiatrist who returns to the insane asy...,\n Director:\nDavid F. Sandberg\n,NaN,NaN,NaN

### Dirty Data
- column name for MOVIES should be TITLE because it also contains series, tv movies, Video, TV Short, Video Game and tv specials.(`Validity`)
- YEAR, GENRE, RATING, VOTES, RunTime and Gross have missing values.(`Completeness`)
- There 431 duplicate rows.(`Accuracy`)
- VOTES and GROSS should be int and float.
- In genre, there is Drama and drama which can cause confusion.

### Messy Data
- In YEAR column, start year and end year of movies are in a form of tuple and there is version to distinguish between movies. There should be separate columns for them.
- There should be a type column which what is the type.
- "\n" in start of string in GENRE column. 
- "\n" in start of string in ONE-LINE and also when there is written add a plot then there is "\n" both infront and at the end of the string.
- "\n" in STARS column.
- STARS column should be divided into two columns.

In [7]:
movies["YEAR"].unique()

array(['(2021)', '(2021– )', '(2010–2022)', '(2013– )', '(2020– )',
       '(2006–2013)', '(2019– )', '(2016–2021)', '(2011– )', '(2005– )',
       '(2008–2013)', '(2017– )', '(2017–2021)', '(2016– )',
       '(1994–2004)', '(2014– )', '(2013–2020)', '(2015– )',
       '(2005–2020)', '(2013–2022)', '(2003– )', '(2009–2020)',
       '(I) (2018– )', '(2010–2015)', '(2011–2019)', '(2015–2020)',
       '(2005–2014)', '(2009–2015)', '(2008–2014)', '(2016–2018)',
       '(2009–2017)', '(2020)', '(2018–2021)', '(2017–2020)',
       '(1987–1994)', '(2018– )', '(2012– )', '(2014–2020)',
       '(2011–2018)', '(2005–2017)', '(2017)', '(2007–2015)',
       '(2000–2007)', '(II) (2007– )', '(1993)', '(1999–2022)',
       '(2015–2018)', '(2014–2019)', '(2016)', '(2012–2020)',
       '(2013–2019)', '(2007–2012)', '(2011–2020)', '(2010–2017)',
       '(2000–2015)', '(2015–2021)', '(2001)', '(1997– )', '(2011–2017)',
       '(1993–1999)', '(1989–1998)', '(2010–2013)', '(2010–2020)',
       '(2003–2019)', '(I) (2019)', '(2017–2019)', '(1975)',
       '(2005–2008)', '(1995–2001)', '(2006)', '(2015–2017)',
       '(2008–2020)', '(1984–1996)', '(2010– )', '(2014)', '(2000)',
       '(2013–2018)', '(2009–2016)', '(2016–2020)', '(2021 TV Special)',
       '(2003)', '(1998–2003)', '(I) (2017)', '(1966–1969)', '(2009– )',
       '(2019)', '(1990–1991)', '(2012)', '(1995)', '(2020–2021)',
       '(2013–2017)', '(2015)', '(2019–2020)', '(2017–2018)',
       '(2013–2015)', '(2012–2017)', '(I) (2013–2016)', '(2002)',
       '(I) (2020)', '(III) (2021)', '(2018)', '(II) (2016)', '(1976)',
       '(1978)', '(2016–2019)', '(2009–2014)', '(2022)', '(2011–2014)',
       '(2007–2013)', '(2006–2007)', '(2002–2007)', '(2014–2017)',
       '(2010–2019)', '(2008– )', '(2012–2019)', '(2014–2016)',
       '(2009–2012)', '(2018–2020)', '(2001–2005)', '(2011–2015)',
       '(2014–2018)', '(2015–2019)', '(1982–1993)', '(1998– )', '(1968)',
       '(2010–2018)', '(2014–2021)', '(2007–2010)', '(2011)',
       '(2013–2021)', '(1990–1996)', '(2004)', '(2007–2014)',
       '(1996–2001)', '(2013)', '(2008)', '(1999–2000)', '(2012–2014)',
       '(I) (2013)', '(2012–2018)', '(2018–2019)', '(2009–2013)',
       '(1971)', '(2004– )', '(1989)', '(1998)', '(2001–2018)',
       '(1987–1995)', '(I) (2014)', '(1998–2020)', '(I) (2015)', '(1997)',
       '(2004–2013)', '(2002– )', '(2010)', '(I) (2016)', '(II) (2017– )',
       '(I) (2018)', '(I) (2021)', '(2004–2012)', '(2019–2021)',
       '(IV) (2020)', '(2006–2010)', '(2006–2012)', '(1996)',
       '(1994–2000)', '(II) (2020)', '(1980)', '(I) (2011)',
       '(1995–1996)', '(2016–2017)', '(1993–1996)', '(II) (2019– )',
       '(2009)', '(1962)', '(1991)', '(2022– )', '(II) (2017)',
       '(I) (2012)', '(1984)', '(2011–2016)', '(2009–2019)',
       '(II) (2020– )', '(2006–2021)', '(I) (2010)', '(2012–2015)',
       '(I) (2013–2014)', '(1960)', '(1988)', '(2007)', '(1987)',
       '(2010–2011)', '(1969)', '(2006–2011)', '(II) (2019)', '(1961)',
       '(1979)', '(II) (2022)', '(2014–2015)', '(1956)', '(2013–2016)',
       '(III) (2018)', '(2005)', '(II) (2012– )', '(II) (2013)', '(1983)',
       '(2002–2019)', '(2013 TV Movie)', '(II) (2015)', '(I) (2012–2015)',
       '(1975–1979)', '(1990)', nan, '(II) (2018)', '(IV) (2021)',
       '(2015–2016)', '(1995–1998)', '(1986)', '(2012–2013)', '(1966)',
       '(2011–2012)', '(2011–2021)', '(2016 Video)', '(2017 TV Movie)',
       '(2009–2011)', '(2004–2018)', '(1967)', '(1984– )', '(1994)',
       '(2003–2006)', '(III) (2015)', '(1974)', '(2000–2004)',
       '(1984–2021)', '(I)', '(II) (2021)', '(1994–1999)', '(III)',
       '(1992)', '(1969–1974)', '(2012–2016)', '(2013–2014)',
       '(I) (2008)', '(1958)', '(2008–2009)', '(II) (2004)',
       '(III) (2019)', '(2006–2009)', '(2011–2013)', '(2007–2008)',
       '(1988–1999)', '(2010–2012)', '(2010–2014)', '(II) (2012)',
       '(1932)', '(2014 TV Movie)', '(1941)', '(2006– )', '(1992–1995)',
       '(2016 TV Special)', '(2020 TV Movie)', '(2008–2010)', '(II)',
       '(2020 Video)', '(1999– )', '(1950)', '(2020 TV Special)',
       '(1992–2014)', '(2002–2005)', '(2013 TV Special)', '(I) (2021– )',
       '(1999)', '(2016 TV Movie)', '(XII)', '(VII)', '(2021 TV Movie)',
       '(1983– )', '(1996 Video)', '(1993 TV Movie)', '(2018 TV Movie)',
       '(2005–2009)', '(2001–2002)', '(2015 TV Movie)', '(I) (2020– )',
       '(2011 Video)', '(2008 Video)', '(2012 Video)', '(1946)',
       '(II) (2014)', '(2019 Video)', '(1981–1989)', '(IV) (2016)',
       '(III) (2016)', '(2019 TV Movie)', '(1952)', '(2007 Video)',
       '(2000–2014)', '(1992– )', '(1957)', '(2003–2007)', '(IV)',
       '(2008–2017)', '(2008–2019)', '(1998–2000)', '(I) (2004)',
       '(2007–2016)', '(2017 TV Special)', '(2009 TV Movie)',
       '(2013 Video)', '(2017 Video)', '(1994–1996)', '(IV) (2017)',
       '(IV) (2018)', '(2007– )', '(1954)', '(2012 TV Movie)', '(1995– )',
       '(1982)', '(1955)', '(2014 TV Short)', '(I) (2022– )',
       '(I) (2019–2020)', '(1975 TV Movie)', '(2019 TV Special)',
       '(2015 TV Special)', '(2015 TV Short)', '(2018 TV Special)',
       '(1948)', '(2014 Video)', '(VI) (2014)', '(2003–2013)',
       '(2021 Video)', '(1947)', '(2001– )', '(II) (2021– )',
       '(1997–2000)', '(III) (2020)', '(I) (2019– )', '(1993– )',
       '(1977)', '(I) (2009)', '(V)', '(2023)', '(I) (2000)',
       '(TV Special)', '(II) (2011)', '(TV Movie)', '(1945)',
       '(2015 Video)', '(III) (2010)', '(2009 Video)', '(1998–2002)',
       '(2008 TV Movie)', '(2019 TV Short)', '(2004 Video)',
       '(II) (1998)', '(2014 TV Special)', '(1953)', '(1985)', '(VIII)',
       '(1973)', '(2012 TV Special)', '(V) (2016)', '(1972)',
       '(V) (2018)', '(II) (2010)', '(2021 TV Short)', '(VI) (2019)',
       '(I) (2005)', '(1965)', '(2010–2016)', '(V) (2010)', '(2005–2013)',
       '(2006 TV Special)', '(2006 Video)', '(2011 TV Movie)',
       '(1988 TV Movie)', '(XXIII)', '(2011 TV Special)',
       '(2020 TV Short)', '(VI) (2018)', '(2008 TV Special)',
       '(1998–1999)', '(I) (2015– )', '(III) (2012)', '(VI)',
       '(2010 TV Special)', '(III) (2017)', '(1993 TV Special)',
       '(2004–2005)', '(1992 Video)', '(1989 TV Special)', '(XI)',
       '(III) (2014)', '(1966 TV Special)', '(1999 TV Movie)',
       '(1987 TV Special)', '(1944)', '(1998 TV Special)',
       '(2006 TV Movie)', '(2022 TV Special)', '(1989 Video)',
       '(1991 TV Special)', '(XLI)', '(IV) (2014)', '(2005 Video)',
       '(2007 TV Special)', '(1965 TV Special)', '(1990 TV Special)',
       '(2001 TV Special)', '(IX)', '(II) (2016– )', '(XIV) (2017)',
       '(2009–2010)', '(XIII)', '(II) (2012–2019)', '(1933)',
       '(II) (2009)', '(2010 Video)', '(2009 TV Special)', '(1938)',
       '(2003 TV Special)', '(Video)', '(2001 TV Movie)', '(VI) (2016)',
       '(III) (2011)', '(2007 TV Movie)', '(2017 TV Short)',
       '(2018 Video)', '(2000 Video)', '(1995 Video)', '(2003 Video)',
       '(II) (2016 TV Movie)', '(1998 Video)', '(2005 TV Special)',
       '(2004–2009)', '(2018 Video Game)', '(1988– )', '(1985– )'],
      dtype=object)

In [8]:
movies["ONE-LINE"].sample(4)

1169    \nA group of unique characters from dramatical...
1598    \nWhen former LAPD officer Brett Anderson take...
2313    \nHigh-school student Ed Wallis enters into a ...
1831    \nIntense look inside the world of junior coll...
Name: ONE-LINE, dtype: object

In [9]:
movies["STARS"][0]

'\n    Director:\nPeter Thorwarth\n| \n    Stars:\nPeri Baumeister, \nCarl Anton Koch, \nAlexander Scheer, \nKais Setti\n'

In [10]:
movies[movies["VOTES"].isnull()]

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
24,He-Man and the Masters of the Universe,(2021– ),"\nAnimation, Action, Adventure",NaN,\nEternia's Prince Adam discovers the power of...,\n,NaN,NaN,NaN
214,Sing 2,(2021),"\nAnimation, Adventure, Comedy",NaN,\nBuster Moon and his friends must persuade re...,\n Director:\nGarth Jennings\n| \n Stars...,NaN,NaN,NaN
217,Knives Out 2,(2022),"\nComedy, Crime, Drama",NaN,\nPlot unknown. Sequel to the 2019 film 'Knive...,\n Director:\nRian Johnson\n| \n Stars:\...,NaN,NaN,NaN
222,Don't Look Up,(2021),\nComedy,NaN,"\nThe story of two low-level astronomers, who ...",\n Director:\nAdam McKay\n| \n Stars:\nT...,NaN,145.0,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

#### Checking for duplicates

In [11]:
movies.duplicated().sum()

431

In [12]:
movies[movies.duplicated()]["MOVIES"].value_counts()

MOVIES
Mighty Little Bheem                  58
Power Rangers: Dino Fury             26
I [Heart] Arlo                       18
Buddi                                12
Unrecorded Night                     12
                                     ..
Monster: The Jeffrey Dahmer Story     1
Living Undocumented                   1
Anatomy of a Scandal                  1
Clickbait                             1
The Imperfects                        1
Name: count, Length: 74, dtype: int64

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    9999 non-null   object
 1   YEAR      9355 non-null   object
 2   GENRE     9919 non-null   object
 3   RATING    8179 non-null   float64
 4   ONE-LINE  9999 non-null   object
 5   STARS     9999 non-null   object
 6   VOTES     8179 non-null   object
 7   RunTime   7041 non-null   float64
 8   Gross     460 non-null    object
dtypes: float64(2), object(7)
memory usage: 703.2+ KB

## Data Cleaning

### 1. Completeness

YEAR, GENRE, RATING, VOTES, RunTime and Gross have missing values so we are going to fix it by using unknown and nan in numeric cols.

In [14]:
# year column has 644 missing values
movies["YEAR"] = movies["YEAR"].fillna("Unknown")

In [15]:
movies["YEAR"].isin(["Unknown"]).sum()

644

In [16]:
# genre column has 80 missing values
movies["GENRE"] = movies["GENRE"].fillna("Unknown")

In [17]:
movies["GENRE"].isin(["Unknown"]).sum()

80

### 2. Messy Data

In [18]:
import re
pattern = re.compile(
    r'^(?:\((?P<version>[IVXLCDM]+)\)\s*)?'   # version like (I), (II), etc.
    r'\(?(?P<start>\d{4})?'                   # start year
    r'(?:[–-](?P<end>\d{4}| ))?\)?'           # end year or blank
    r'(?:\s*(?P<type>TV Movie|TV Special|Video Game|Video|Short))?' # type
    , re.IGNORECASE
)

def parse_entry(entry):
    if pd.isna(entry) or entry.strip().lower() == "nan":
        return pd.Series([None, None, None, None])
    
    m = pattern.search(entry)
    if m:
        version = m.group("version")
        start = m.group("start")
        end = m.group("end")
        ent_type = m.group("type")

        # Handle blank end (ongoing series)
        if end == " ":
            end = "Present"

        # Apply logic for default type
        if not ent_type:
            if start and end:  # has a range
                ent_type = "Series"
            elif start and not end:  # just one year
                ent_type = "Movie"

        # For movies → endyear must stay None
        if ent_type == "Movie":
            end = None

        return pd.Series([version, start, end, ent_type])
    
    return pd.Series([None, None, None, None])

In [19]:
new = movies["YEAR"].apply(parse_entry)
new.columns = ["Version","Start_Year","End_Year","Type"]
new

     Version Start_Year End_Year    Type
0       None       2021     None   Movie
1       None       2021  Present  Series
2       None       2010     2022  Series
3       None       2013  Present  Series
4       None       2021     None   Movie
...      ...        ...      ...     ...
9994    None       2021  Present  Series
9995    None       2021  Present  Series
9996    None       2022  Present  Series
9997    None       2021  Present  Series
9998    None       2021  Present  Series

[9999 rows x 4 columns]

**We should remove all the none values**

In [20]:
new.fillna({
    "Version":"NULL",
    "Start_Year":"Unknown",
    "End_Year":"Unknown",
    "Type":"Unknown"
    },
    inplace = True
)

In [21]:
new["Start_Year"].isna().sum()

0

In [22]:
new["End_Year"].isna().sum()

0

In [23]:
new["Type"].isna().sum()

0

In [24]:
new["Version"].isna().sum()

0

In [25]:
new["Type"].value_counts()

Type
Series        4568
Movie         4027
Unknown        732
TV Special     397
TV Movie       162
Video          112
Video Game       1
Name: count, dtype: int64

In [26]:
movies = pd.concat([movies,new],axis=1)

In [27]:
movies.drop(columns="YEAR",inplace=True)

In [28]:
movies

,MOVIES,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,Version,Start_Year,End_Year,Type
0,Blood Red Sky,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,NULL,2021,Unknown,Movie
1,Masters of the Universe: Revelation,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,NULL,2021,Present,Series
2,The Walking Dead,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,NULL,2010,2022,Series
3,Rick and Morty,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,NULL,2013,Present,Series
4,Army of Thieves,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,NULL,2021,Unknown,Movie
...,...,...,...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN,NULL,2021,Present,Series
9995,Arcane,"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN,NULL,2021,Present,Series
9996,Heart of Invictus,"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN,NULL,2022,Present,Series
9997,The Imperfects,"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN,NULL,2021,Present,Series
9998,The Imperfects,"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN,NULL,2021,Present,Series

In [29]:
movies[["GENRE", "ONE-LINE", "STARS"]] = movies[["GENRE", "ONE-LINE", "STARS"]].apply(lambda x : x.str.replace("\n","").str.strip())
movies

,MOVIES,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,Version,Start_Year,End_Year,Type
0,Blood Red Sky,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri Baume...,"21,062",121.0,NaN,NULL,2021,Unknown,Movie
1,Masters of the Universe: Revelation,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michelle Gellar, Lena ...","17,870",25.0,NaN,NULL,2021,Present,Series
2,The Walking Dead,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman Reedus, Melissa M...","885,805",44.0,NaN,NULL,2010,2022,Series
3,Rick and Morty,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Parnell, Spencer G...","414,849",23.0,NaN,NULL,2013,Present,Series
4,Army of Thieves,"Action, Crime, Horror",NaN,"A prequel, set before the events of Army of th...",Director:Matthias Schweighöfer| Stars:Matt...,NaN,NaN,NaN,NULL,2021,Unknown,Movie
...,...,...,...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,"Stars:Morgan Taylor Campbell, Chris Cope, Iñak...",NaN,NaN,NaN,NULL,2021,Present,Series
9995,Arcane,"Animation, Action, Adventure",NaN,Add a Plot,,NaN,NaN,NaN,NULL,2021,Present,Series
9996,Heart of Invictus,"Documentary, Sport",NaN,Add a Plot,Director:Orlando von Einsiedel| Star:Princ...,NaN,NaN,NaN,NULL,2022,Present,Series
9997,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,Director:Jovanka Vuckovic| Stars:Morgan Ta...,NaN,NaN,NaN,NULL,2021,Present,Series
9998,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,Director:Jovanka Vuckovic| Stars:Morgan Ta...,NaN,NaN,NaN,NULL,2021,Present,Series

In [30]:
movies["STARS"][0]

'Director:Peter Thorwarth|     Stars:Peri Baumeister, Carl Anton Koch, Alexander Scheer, Kais Setti'

In [31]:
movies[movies["STARS"] == ""]

,MOVIES,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,Version,Start_Year,End_Year,Type
24,He-Man and the Masters of the Universe,"Animation, Action, Adventure",NaN,Eternia's Prince Adam discovers the power of G...,,NaN,NaN,NaN,NULL,2021,Present,Series
1027,Myth & Mogul: John DeLorean,"Documentary, Biography, Crime",7.0,"In the automotive world, John DeLorean rose fr...",,213,NaN,NaN,NULL,2021,Present,Series
1380,Love is Blind: After the Altar,Reality-TV,5.4,"Couples from ""Love is Blind"" celebrate their w...",,39,45.0,NaN,NULL,2021,Present,Series
1419,Avatar: The Last Airbender,"Action, Adventure, Fantasy",NaN,Live-action adaptation of the animated series ...,,NaN,NaN,NaN,NULL,Unknown,Unknown,Unknown
1454,Cocaine Cowboys: The Kings of Miami,"Documentary, Crime, History",NaN,Two childhood friends go from high school drop...,,NaN,NaN,NaN,NULL,2021,Unknown,Movie
...,...,...,...,...,...,...,...,...,...,...,...,...
9972,Sonic Prime,"Animation, Action, Adventure",NaN,Add a Plot,,NaN,NaN,NaN,NULL,2022,Present,Series
9973,Sonic Prime,"Animation, Action, Adventure",NaN,Add a Plot,,NaN,NaN,NaN,NULL,2022,Present,Series
9974,Sonic Prime,"Animation, Action, Adventure",NaN,Add a Plot,,NaN,NaN,NaN,NULL,2022,Present,Series
9986,The Last Kingdom,"Action, Drama, History",NaN,Add a Plot,,NaN,NaN,NaN,NULL,2015,Present,Series
9995,Arcane,"Animation, Action, Adventure",NaN,Add a Plot,,NaN,NaN,NaN,NULL,2021,Present,Series

In [32]:
def co(a):
    if a == 0:
        return False
    return True
a = movies[(movies == "").sum(axis=1).apply(co)]
a

,MOVIES,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,Version,Start_Year,End_Year,Type
24,He-Man and the Masters of the Universe,"Animation, Action, Adventure",NaN,Eternia's Prince Adam discovers the power of G...,,NaN,NaN,NaN,NULL,2021,Present,Series
1027,Myth & Mogul: John DeLorean,"Documentary, Biography, Crime",7.0,"In the automotive world, John DeLorean rose fr...",,213,NaN,NaN,NULL,2021,Present,Series
1380,Love is Blind: After the Altar,Reality-TV,5.4,"Couples from ""Love is Blind"" celebrate their w...",,39,45.0,NaN,NULL,2021,Present,Series
1419,Avatar: The Last Airbender,"Action, Adventure, Fantasy",NaN,Live-action adaptation of the animated series ...,,NaN,NaN,NaN,NULL,Unknown,Unknown,Unknown
1454,Cocaine Cowboys: The Kings of Miami,"Documentary, Crime, History",NaN,Two childhood friends go from high school drop...,,NaN,NaN,NaN,NULL,2021,Unknown,Movie
...,...,...,...,...,...,...,...,...,...,...,...,...
9972,Sonic Prime,"Animation, Action, Adventure",NaN,Add a Plot,,NaN,NaN,NaN,NULL,2022,Present,Series
9973,Sonic Prime,"Animation, Action, Adventure",NaN,Add a Plot,,NaN,NaN,NaN,NULL,2022,Present,Series
9974,Sonic Prime,"Animation, Action, Adventure",NaN,Add a Plot,,NaN,NaN,NaN,NULL,2022,Present,Series
9986,The Last Kingdom,"Action, Drama, History",NaN,Add a Plot,,NaN,NaN,NaN,NULL,2015,Present,Series
9995,Arcane,"Animation, Action, Adventure",NaN,Add a Plot,,NaN,NaN,NaN,NULL,2021,Present,Series

In [33]:
(a["STARS"] == "").sum()

456

In [34]:
movies["STARS"] = movies["STARS"].replace("","Unknown")

In [35]:
(movies["STARS"] == "").sum()

0

In [36]:
# others are "Unknown"
movies["STARS"].apply(lambda x:(x[0]=="S" or x[0]=="D")).sum()

9543

In [37]:
movies["STARS"][0]

'Director:Peter Thorwarth|     Stars:Peri Baumeister, Carl Anton Koch, Alexander Scheer, Kais Setti'

In [38]:
def extract_director_and_stars(stars: str) -> pd.Series:
    if stars.startswith("Director"):
        try:
            director, actors = stars.split("|", 1)  # only split once
            return pd.Series([director.strip()[9:].strip(":"), actors.strip()[5:].strip(":")])  
        except ValueError:
             # If "|" is missing but Director exists
             return pd.Series([stars[9:].strip(":"), "Unknown"])
    elif stars.startswith("Star"):
        return pd.Series(["Unknown", stars.strip()[5:].strip(":")])
    
    elif stars.startswith("Unknown"):
        return pd.Series(["Unknown", "Unknown"])
    
Directors_and_Actors = movies["STARS"].apply(extract_director_and_stars)

In [39]:
Directors_and_Actors.columns = ["Director/Directors","Actor/Actors"]
Directors_and_Actors

         Director/Directors                                       Actor/Actors
0           Peter Thorwarth  Peri Baumeister, Carl Anton Koch, Alexander Sc...
1                   Unknown  Chris Wood, Sarah Michelle Gellar, Lena Headey...
2                   Unknown  Andrew Lincoln, Norman Reedus, Melissa McBride...
3                   Unknown  Justin Roiland, Chris Parnell, Spencer Grammer...
4     Matthias Schweighöfer  Matthias Schweighöfer, Nathalie Emmanuel, Ruby...
...                     ...                                                ...
9994                Unknown  Morgan Taylor Campbell, Chris Cope, Iñaki Godo...
9995                Unknown                                            Unknown
9996  Orlando von Einsiedel                                       Prince Harry
9997       Jovanka Vuckovic  Morgan Taylor Campbell, Iñaki Godoy, Rhianna J...
9998       Jovanka Vuckovic  Morgan Taylor Campbell, Jennifer Cheon Garcia,...

[9999 rows x 2 columns]

In [40]:
movies = pd.concat([movies,Directors_and_Actors],axis=1).drop(columns="STARS")

In [41]:
movies

,MOVIES,GENRE,RATING,ONE-LINE,VOTES,RunTime,Gross,Version,Start_Year,End_Year,Type,Director/Directors,Actor/Actors
0,Blood Red Sky,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,"21,062",121.0,NaN,NULL,2021,Unknown,Movie,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexander Sc..."
1,Masters of the Universe: Revelation,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"17,870",25.0,NaN,NULL,2021,Present,Series,Unknown,"Chris Wood, Sarah Michelle Gellar, Lena Headey..."
2,The Walking Dead,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"885,805",44.0,NaN,NULL,2010,2022,Series,Unknown,"Andrew Lincoln, Norman Reedus, Melissa McBride..."
3,Rick and Morty,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"414,849",23.0,NaN,NULL,2013,Present,Series,Unknown,"Justin Roiland, Chris Parnell, Spencer Grammer..."
4,Army of Thieves,"Action, Crime, Horror",NaN,"A prequel, set before the events of Army of th...",NaN,NaN,NaN,NULL,2021,Unknown,Movie,Matthias Schweighöfer,"Matthias Schweighöfer, Nathalie Emmanuel, Ruby..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Unknown,"Morgan Taylor Campbell, Chris Cope, Iñaki Godo..."
9995,Arcane,"Animation, Action, Adventure",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Unknown,Unknown
9996,Heart of Invictus,"Documentary, Sport",NaN,Add a Plot,NaN,NaN,NaN,NULL,2022,Present,Series,Orlando von Einsiedel,Prince Harry
9997,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Jovanka Vuckovic,"Morgan Taylor Campbell, Iñaki Godoy, Rhianna J..."
9998,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Jovanka Vuckovic,"Morgan Taylor Campbell, Jennifer Cheon Garcia,..."

* Correcting the datatype of Type column into Category

In [42]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MOVIES              9999 non-null   object
 1   GENRE               9999 non-null   object
 2   RATING              8179 non-null   float64
 3   ONE-LINE            9999 non-null   object
 4   VOTES               8179 non-null   object
 5   RunTime             7041 non-null   float64
 6   Gross               460 non-null    object
 7   Version             9999 non-null   object
 8   Start_Year          9999 non-null   object
 9   End_Year            9999 non-null   object
 10  Type                9999 non-null   object
 11  Director/Directors  9999 non-null   object
 12  Actor/Actors        9999 non-null   object
dtypes: float64(2), object(11)
memory usage: 1015.7+ KB

In [43]:
movies["Type"] = movies["Type"].astype("category")

In [44]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MOVIES              9999 non-null   object
 1   GENRE               9999 non-null   object
 2   RATING              8179 non-null   float64
 3   ONE-LINE            9999 non-null   object
 4   VOTES               8179 non-null   object
 5   RunTime             7041 non-null   float64
 6   Gross               460 non-null    object
 7   Version             9999 non-null   object
 8   Start_Year          9999 non-null   object
 9   End_Year            9999 non-null   object
 10  Type                9999 non-null   category
 11  Director/Directors  9999 non-null   object
 12  Actor/Actors        9999 non-null   object
dtypes: category(1), float64(2), object(10)
memory usage: 947.6+ KB

### Handling Duplicates

In [45]:
movies.duplicated().sum()

431

In [46]:
movies[movies.duplicated()]

,MOVIES,GENRE,RATING,ONE-LINE,VOTES,RunTime,Gross,Version,Start_Year,End_Year,Type,Director/Directors,Actor/Actors
6833,Mighty Little Bheem,"Animation, Short, Adventure",NaN,Add a Plot,NaN,NaN,NaN,NULL,2019,Present,Series,"Rajiv Chilaka, Krishna Mohan Chintapatla",Unknown
6835,Mighty Little Bheem,"Animation, Short, Adventure",9.0,Add a Plot,6,NaN,NaN,NULL,2019,Present,Series,"Rajiv Chilaka, Krishna Mohan Chintapatla",Unknown
6836,Mighty Little Bheem,"Animation, Short, Adventure",9.0,Add a Plot,6,NaN,NaN,NULL,2019,Present,Series,"Rajiv Chilaka, Krishna Mohan Chintapatla",Unknown
6837,Mighty Little Bheem,"Animation, Short, Adventure",NaN,Add a Plot,NaN,NaN,NaN,NULL,2019,Present,Series,"Rajiv Chilaka, Krishna Mohan Chintapatla",Unknown
6838,Mighty Little Bheem,"Animation, Short, Adventure",NaN,Add a Plot,NaN,NaN,NaN,NULL,2019,Present,Series,"Rajiv Chilaka, Krishna Mohan Chintapatla",Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,1899,"Drama, History, Horror",NaN,Add a Plot,NaN,NaN,NaN,NULL,2022,Present,Series,Baran bo Odar,Unknown
9990,1899,"Drama, History, Horror",NaN,Add a Plot,NaN,NaN,NaN,NULL,2022,Present,Series,Baran bo Odar,Unknown
9991,1899,"Drama, History, Horror",NaN,Add a Plot,NaN,NaN,NaN,NULL,2022,Present,Series,Baran bo Odar,Unknown
9992,1899,"Drama, History, Horror",NaN,Add a Plot,NaN,NaN,NaN,NULL,2022,Present,Series,Baran bo Odar,Unknown
9994,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Unknown,"Morgan Taylor Campbell, Chris Cope, Iñaki Godo..."

In [47]:
movies[movies.duplicated()]["MOVIES"].value_counts()

MOVIES
Mighty Little Bheem                  58
Power Rangers: Dino Fury             26
I [Heart] Arlo                       18
Buddi                                12
Unrecorded Night                     12
                                     ..
Monster: The Jeffrey Dahmer Story     1
Living Undocumented                   1
Anatomy of a Scandal                  1
Clickbait                             1
The Imperfects                        1
Name: count, Length: 74, dtype: int64

In [48]:
movies.drop_duplicates(inplace=True)

In [49]:
movies.duplicated().sum()

0

In [50]:
movies

,MOVIES,GENRE,RATING,ONE-LINE,VOTES,RunTime,Gross,Version,Start_Year,End_Year,Type,Director/Directors,Actor/Actors
0,Blood Red Sky,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,"21,062",121.0,NaN,NULL,2021,Unknown,Movie,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexander Sc..."
1,Masters of the Universe: Revelation,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"17,870",25.0,NaN,NULL,2021,Present,Series,Unknown,"Chris Wood, Sarah Michelle Gellar, Lena Headey..."
2,The Walking Dead,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"885,805",44.0,NaN,NULL,2010,2022,Series,Unknown,"Andrew Lincoln, Norman Reedus, Melissa McBride..."
3,Rick and Morty,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"414,849",23.0,NaN,NULL,2013,Present,Series,Unknown,"Justin Roiland, Chris Parnell, Spencer Grammer..."
4,Army of Thieves,"Action, Crime, Horror",NaN,"A prequel, set before the events of Army of th...",NaN,NaN,NaN,NULL,2021,Unknown,Movie,Matthias Schweighöfer,"Matthias Schweighöfer, Nathalie Emmanuel, Ruby..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,Totenfrau,"Drama, Thriller",NaN,Add a Plot,NaN,NaN,NaN,NULL,2022,Present,Series,Nicolai Rohde,"Felix Klare, Romina Küper, Anna Maria Mühe, Ro..."
9995,Arcane,"Animation, Action, Adventure",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Unknown,Unknown
9996,Heart of Invictus,"Documentary, Sport",NaN,Add a Plot,NaN,NaN,NaN,NULL,2022,Present,Series,Orlando von Einsiedel,Prince Harry
9997,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Jovanka Vuckovic,"Morgan Taylor Campbell, Iñaki Godoy, Rhianna J..."
9998,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Jovanka Vuckovic,"Morgan Taylor Campbell, Jennifer Cheon Garcia,..."

In [51]:
movies.columns = ['Title', 'Genre', 'Rating', 'One_Line', 'Votes', 'RunTime', 'Gross',
       'Version', 'Start_Year', 'End_Year', 'Type', 'Director/Directors',
       'Actor/Actors']

In [52]:
movies

,Title,Genre,Rating,One_Line,Votes,RunTime,Gross,Version,Start_Year,End_Year,Type,Director/Directors,Actor/Actors
0,Blood Red Sky,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,"21,062",121.0,NaN,NULL,2021,Unknown,Movie,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexander Sc..."
1,Masters of the Universe: Revelation,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"17,870",25.0,NaN,NULL,2021,Present,Series,Unknown,"Chris Wood, Sarah Michelle Gellar, Lena Headey..."
2,The Walking Dead,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"885,805",44.0,NaN,NULL,2010,2022,Series,Unknown,"Andrew Lincoln, Norman Reedus, Melissa McBride..."
3,Rick and Morty,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"414,849",23.0,NaN,NULL,2013,Present,Series,Unknown,"Justin Roiland, Chris Parnell, Spencer Grammer..."
4,Army of Thieves,"Action, Crime, Horror",NaN,"A prequel, set before the events of Army of th...",NaN,NaN,NaN,NULL,2021,Unknown,Movie,Matthias Schweighöfer,"Matthias Schweighöfer, Nathalie Emmanuel, Ruby..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,Totenfrau,"Drama, Thriller",NaN,Add a Plot,NaN,NaN,NaN,NULL,2022,Present,Series,Nicolai Rohde,"Felix Klare, Romina Küper, Anna Maria Mühe, Ro..."
9995,Arcane,"Animation, Action, Adventure",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Unknown,Unknown
9996,Heart of Invictus,"Documentary, Sport",NaN,Add a Plot,NaN,NaN,NaN,NULL,2022,Present,Series,Orlando von Einsiedel,Prince Harry
9997,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Jovanka Vuckovic,"Morgan Taylor Campbell, Iñaki Godoy, Rhianna J..."
9998,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Jovanka Vuckovic,"Morgan Taylor Campbell, Jennifer Cheon Garcia,..."

In [53]:
movies["Genre"] = movies["Genre"].str.title()

In [54]:
movies

,Title,Genre,Rating,One_Line,Votes,RunTime,Gross,Version,Start_Year,End_Year,Type,Director/Directors,Actor/Actors
0,Blood Red Sky,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,"21,062",121.0,NaN,NULL,2021,Unknown,Movie,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexander Sc..."
1,Masters of the Universe: Revelation,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"17,870",25.0,NaN,NULL,2021,Present,Series,Unknown,"Chris Wood, Sarah Michelle Gellar, Lena Headey..."
2,The Walking Dead,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"885,805",44.0,NaN,NULL,2010,2022,Series,Unknown,"Andrew Lincoln, Norman Reedus, Melissa McBride..."
3,Rick and Morty,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"414,849",23.0,NaN,NULL,2013,Present,Series,Unknown,"Justin Roiland, Chris Parnell, Spencer Grammer..."
4,Army of Thieves,"Action, Crime, Horror",NaN,"A prequel, set before the events of Army of th...",NaN,NaN,NaN,NULL,2021,Unknown,Movie,Matthias Schweighöfer,"Matthias Schweighöfer, Nathalie Emmanuel, Ruby..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,Totenfrau,"Drama, Thriller",NaN,Add a Plot,NaN,NaN,NaN,NULL,2022,Present,Series,Nicolai Rohde,"Felix Klare, Romina Küper, Anna Maria Mühe, Ro..."
9995,Arcane,"Animation, Action, Adventure",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Unknown,Unknown
9996,Heart of Invictus,"Documentary, Sport",NaN,Add a Plot,NaN,NaN,NaN,NULL,2022,Present,Series,Orlando von Einsiedel,Prince Harry
9997,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Jovanka Vuckovic,"Morgan Taylor Campbell, Iñaki Godoy, Rhianna J..."
9998,The Imperfects,"Adventure, Drama, Fantasy",NaN,Add a Plot,NaN,NaN,NaN,NULL,2021,Present,Series,Jovanka Vuckovic,"Morgan Taylor Campbell, Jennifer Cheon Garcia,..."

In [55]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9568 entries, 0 to 9998
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               9568 non-null   object
 1   Genre               9568 non-null   object
 2   Rating              8168 non-null   float64
 3   One_Line            9568 non-null   object
 4   Votes               8168 non-null   object
 5   RunTime             7008 non-null   float64
 6   Gross               460 non-null    object
 7   Version             9568 non-null   object
 8   Start_Year          9568 non-null   object
 9   End_Year            9568 non-null   object
 10  Type                9568 non-null   category
 11  Director/Directors  9568 non-null   object
 12  Actor/Actors        9568 non-null   object
dtypes: category(1), float64(2), object(10)
memory usage: 981.4+ KB

### Exporting The Dataset

In [56]:
movies.to_csv("cleaned_movies.csv")